# Generated by Django 4.2.7 on 2023-11-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumsubscription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients'),
        ),
    ]
