# Generated by Django 4.2.7 on 2023-11-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0007_remove_staffs_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('staffs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_treated', models.DateField(auto_now=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField()),
                ('medication', models.TextField()),
                ('cost', models.CharField(max_length=100)),
                ('patient_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
