# Generated by Django 3.2.21 on 2023-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='position',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Administrator')], default='doctor', max_length=20),
        ),
    ]
