# Generated by Django 4.2.7 on 2023-11-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20231120_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='passcode',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
