# Generated by Django 4.2.7 on 2023-11-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staffs_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='passcode',
        ),
    ]
